import Link from "next/link";
import { Download, Plus, Settings2, Upload } from "lucide-react";
import { assertPermission } from "@/lib/authorization";
import { PERMISSIONS } from "@/lib/permission-catalog";
import { prisma } from "@/lib/prisma";
import { requireSessionUser } from "@/lib/session";
import { createWorkOrderAction, createWorkOrderFieldAction, importWorkOrdersAction } from "@/modules/production/actions";
import ui from "../../management.module.css";

export default async function WorkOrdersPage() {
  const { authorization } = await requireSessionUser();
  assertPermission(authorization, PERMISSIONS.CAPACITY_VIEW);
  if (!authorization.companyId) throw new Error("Aktif firma seçilmedi.");
  const companyId = authorization.companyId;
  const canManage = authorization.isPlatformAdmin || authorization.permissions.has(PERMISSIONS.CAPACITY_MANAGE);
  const [stations, tools, fields, workOrders] = await Promise.all([
    prisma.productionStation.findMany({ where: { companyId, isActive: true, workCenter: { isActive: true } }, include: { workCenter: { select: { name: true } } }, orderBy: [{ workCenter: { name: "asc" } }, { name: "asc" }] }),
    prisma.productionTool.findMany({ where: { companyId, isActive: true }, orderBy: { name: "asc" } }),
    prisma.productionCustomField.findMany({ where: { companyId, entity: "WORK_ORDER", isActive: true }, orderBy: { displayOrder: "asc" } }),
    prisma.productionWorkOrder.findMany({ where: { companyId }, include: { station: { select: { name: true } }, workCenter: { select: { name: true } } }, orderBy: [{ dueDate: "asc" }, { createdAt: "desc" }], take: 100 }),
  ]);
  return <div className={ui.managementPage}>
    <header className={ui.pageHeader}><div className={ui.headerCopy}><p className={ui.kicker}>Üretim planlama</p><h1 className={ui.pageTitle}>İş Emirleri ve İş Yükü</h1><p className={ui.pageDescription}>Manuel iş emri ekleyin veya kendi alanlarınıza göre şablonunuzu hazırlayıp içeri aktarın.</p></div><div className={ui.headerActions}><a href="/dashboard/production/work-orders/template-xlsx" className={ui.secondaryAction}><Download size={16}/>Excel şablonunu indir</a><a href="/dashboard/production/work-orders/template" className={ui.secondaryAction}><Download size={16}/>CSV şablonu</a><Link href="/dashboard/production/gantt" className={ui.primaryAction}>Gantt’a geç</Link></div></header>
    {canManage && <section className={ui.splitLayout}>
      <form action={createWorkOrderAction} className={`${ui.surface} ${ui.formShell}`}>
        <div className={ui.sectionHeading}><div><h2>Yeni iş emri</h2><p>İstasyon ve çevrim standardına göre yaklaşık süre otomatik hesaplanır.</p></div><Plus size={18}/></div>
        <div className={ui.formGridThree}><label className={ui.formField}><span>İş emri no</span><input name="workOrderNo" required maxLength={96} placeholder="IE-2026-0001" /></label><label className={ui.formField}><span>Sipariş no</span><input name="orderNo" maxLength={96} placeholder="SIP-0001" /></label><label className={ui.formField}><span>Termin tarihi</span><input name="dueDate" type="date" /></label><label className={ui.formField}><span>Parça kodu</span><input name="itemCode" required maxLength={96} placeholder="PRT-1001" /></label><label className={ui.formField}><span>Parça adı</span><input name="itemName" maxLength={255} /></label><label className={ui.formField}><span>Miktar</span><input name="quantity" required type="number" min="0.001" step="0.001" /></label><label className={ui.formField}><span>İstasyon</span><select name="stationId" required defaultValue=""><option value="" disabled>Seçin</option>{stations.map((station) => <option key={station.id} value={station.id}>{station.workCenter.name} · {station.name}</option>)}</select></label><label className={ui.formField}><span>Kalıp / aparat</span><select name="toolId"><option value="">Yok</option>{tools.map((tool) => <option key={tool.id} value={tool.id}>{tool.name}</option>)}</select></label><label className={ui.formField}><span>Çevrim süresi (sn)</span><input name="cycleSeconds" type="number" min="1" step="1" placeholder="Standarttan bulunur" /></label><label className={ui.formField}><span>Göz adedi</span><input name="cavityCount" type="number" min="1" step="1" placeholder="Standarttan bulunur" /></label><label className={ui.formField}><span>Hazırlık süresi (dk)</span><input name="setupMinutes" type="number" min="0" step="1" placeholder="Standarttan bulunur" /></label>{fields.map((field) => <label className={ui.formField} key={field.id}><span>{field.label}{field.isRequired ? " *" : ""}</span>{field.fieldType === "SELECT" ? <select name={`custom_${field.fieldKey}`} required={field.isRequired}><option value="">Seçin</option>{(field.optionsJson ? JSON.parse(field.optionsJson) as string[] : []).map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input name={`custom_${field.fieldKey}`} required={field.isRequired} type={field.fieldType === "NUMBER" ? "number" : field.fieldType === "DATE" ? "date" : "text"} />}</label>)}</div>
        <div className={ui.formActions}><button className={ui.primaryAction} type="submit"><Plus size={16}/>İş emrini planla</button></div>
      </form>
      <form action={createWorkOrderFieldAction} className={`${ui.surface} ${ui.formShell}`}>
        <div className={ui.sectionHeading}><div><h2>Excel ve plan alanları</h2><p>Buradaki alanlar formda, şablonda ve Gantt filtrelerinde kullanılabilir.</p></div><Settings2 size={18}/></div>
        <div className={ui.formGrid}><label className={ui.formField}><span>Alan anahtarı</span><input name="fieldKey" required pattern="[a-z][a-z0-9_]{1,62}" placeholder="musteri_grubu" /></label><label className={ui.formField}><span>Görünen ad</span><input name="label" required placeholder="Müşteri grubu" /></label><label className={ui.formField}><span>Tür</span><select name="fieldType"><option value="TEXT">Metin</option><option value="NUMBER">Sayı</option><option value="DATE">Tarih</option><option value="SELECT">Seçim</option><option value="BOOLEAN">Evet / Hayır</option></select></label><label className={ui.formField}><span>Seçenekler</span><input name="optionsJson" placeholder='Seçim için: [&quot;A&quot;,&quot;B&quot;]' /></label><label className={`${ui.checkField} ${ui.formFullWidth}`}><input name="isRequired" type="checkbox" /> Zorunlu alan</label></div>
        <div className={ui.formActions}><button className={ui.secondaryAction} type="submit"><Settings2 size={16}/>Alan ekle</button></div>
        <div>{fields.length ? <ul className={ui.detailList}>{fields.map((field) => <li key={field.id} className={ui.detailRow}><span>{field.label}</span><strong>{field.fieldType}</strong></li>)}</ul> : <p className={ui.helpText}>Henüz firma tanımlı ek alan bulunmuyor.</p>}</div>
      </form>
    </section>}
    {canManage && <section className={ui.surface}><form action={importWorkOrdersAction} className={ui.formShell}><div className={ui.sectionHeading}><div><h2>Excel / CSV içeri aktar</h2><p>İndirilen şablonu kullanın. Önce tüm satırlar doğrulanır; hatalı dosyada hiçbir kayıt eklenmez.</p></div><Upload size={18}/></div><div className={ui.formGrid}><label className={ui.formField}><span>Dosya</span><input name="file" type="file" accept=".xlsx,.xls,.csv,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" required /></label><div className={ui.formActions}><button className={ui.primaryAction} type="submit"><Upload size={16}/>Dosyayı içeri aktar</button></div></div></form></section>}
    <section className={ui.surface}><div className={ui.sectionHeading}><div><h2>Planlama kuyruğu</h2><p>İş emri Gantt’ta istasyon sırasına göre yer alır.</p></div><span className={ui.statusNeutral}>{workOrders.length} iş emri</span></div><div className={ui.tableWrap}><table className={ui.dataTable}><thead><tr><th>İş emri / sipariş</th><th>Parça</th><th>İstasyon</th><th>Süre</th><th>Termin</th><th>Durum</th></tr></thead><tbody>{workOrders.length === 0 ? <tr><td colSpan={6} className={ui.emptyCell}>Henüz iş emri eklenmedi.</td></tr> : workOrders.map((order) => <tr key={order.id}><td><strong>{order.workOrderNo}</strong><br/><span>{order.orderNo ?? "Sipariş bilgisi yok"}</span></td><td><strong>{order.itemCode}</strong><br/><span>{order.itemName ?? "—"} · {order.quantity.toString()} adet</span></td><td><strong>{order.station.name}</strong><br/><span>{order.workCenter.name}</span></td><td>{order.calculatedMinutes} dk</td><td>{order.dueDate ? new Intl.DateTimeFormat("tr-TR").format(order.dueDate) : "—"}</td><td><span className={ui.statusNeutral}>{order.status}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
