import { createCompanyRoleAction, updateCompanyRoleAction } from "@/app/dashboard/access-actions";
import { SubmitButton } from "@/app/dashboard/submit-button";
import { assertPermission } from "@/lib/authorization";
import { PERMISSION_GROUPS, PERMISSIONS } from "@/lib/permission-catalog";
import { prisma } from "@/lib/prisma";
import { requireSessionUser } from "@/lib/session";
import styles from "../../page.module.css";

export default async function CompanyRolesPage(props: { searchParams: Promise<{ clone?: string }> }) {
  const { authorization } = await requireSessionUser(); assertPermission(authorization, PERMISSIONS.ACCESS_VIEW); if (!authorization.companyId) throw new Error("Aktif firma seçilmedi.");
  const roles = await prisma.companyRole.findMany({ where: { companyId: authorization.companyId }, include: { permissions: true, _count: { select: { memberships: true } } }, orderBy: [{ isSystem: "desc" }, { name: "asc" }] }); const canManage = authorization.permissions.has(PERMISSIONS.ACCESS_MANAGE);
  const params = await props.searchParams;
  const cloneRole = roles.find((role) => role.id === Number(params.clone));
  const clonePermissions = cloneRole?.permissions.map((item) => item.permission).filter((permission) => authorization.permissions.has(permission)) ?? [];
  return <div className={styles.page}><section className={`glass-panel ${styles.heroCard}`}><div><p className={styles.eyebrow}>Kullanıcılar ve Yetkiler</p><h1 className={styles.title}>Firma Rolleri</h1><p className={styles.subtitle}>Hazır rolleri inceleyin, kopya/özel rol oluşturun ve yalnız sahip olduğunuz izinleri devredin. Pasif rol erişimi genişletmez.</p></div></section>
    {canManage ? <section className={`glass-panel ${styles.sectionCard}`}><div className={styles.sectionHeader}><div><p className={styles.sectionEyebrow}>Özel rol</p><h2 className={styles.sectionTitle}>{cloneRole ? `${cloneRole.name} Rolünü Kopyala` : "Yeni Rol Oluştur"}</h2></div></div><form action={createCompanyRoleAction} className={styles.formGrid}><label className={styles.field}><span>Rol adı</span><input name="name" defaultValue={cloneRole ? `${cloneRole.name} - Kopya` : ""} required/></label><label className={styles.field}><span>Açıklama</span><input name="description" defaultValue={cloneRole ? `${cloneRole.name} rolünden oluşturuldu.` : ""}/></label><PermissionMatrix selected={clonePermissions} editablePermissions={[...authorization.permissions]}/><div className={styles.fullWidthActionRow}><SubmitButton idleLabel="Rolü Oluştur" pendingLabel="Oluşturuluyor..." className={styles.primaryButton}/></div></form></section> : null}
    <div className={styles.reviewCaseList}>{roles.map((role)=><section key={role.id} className={`glass-panel ${styles.sectionCard}`}><form action={updateCompanyRoleAction} className={styles.formGrid}><input type="hidden" name="roleId" value={role.id}/><label className={styles.field}><span>Rol</span><input name="name" defaultValue={role.name} readOnly={!canManage}/></label><div className={styles.detailList}><p><span>Tür</span>{role.isSystem ? "Hazır rol" : "Özel rol"}</p><p><span>Aktif üye</span>{role._count.memberships}</p></div>{canManage ? <label className={styles.checkField}><input type="checkbox" name="isActive" defaultChecked={role.isActive}/><span>Aktif rol</span></label> : null}<PermissionMatrix selected={role.permissions.map((item)=>item.permission)} editablePermissions={canManage ? [...authorization.permissions] : []}/>{canManage ? <div className={styles.fullWidthActionRow}><Link href={`/dashboard/access/roles?clone=${role.id}`} className={styles.secondaryLinkButton}>Bu Rolü Kopyala</Link><SubmitButton idleLabel="Rolü Güncelle" pendingLabel="Güncelleniyor..." className={styles.smallButton}/></div> : null}</form></section>)}</div>
  </div>;
}
function PermissionMatrix({selected,editablePermissions}:{selected:string[];editablePermissions:string[]}) { return <div className={`${styles.permissionMatrix} ${styles.fullWidth}`}>{PERMISSION_GROUPS.map((group)=><fieldset key={group.label} className={styles.scopeFieldset}><legend>{group.label}</legend>{group.items.map(([code,label])=><label key={code} className={styles.checkField}><input type="checkbox" name="permissions" value={code} defaultChecked={selected.includes(code)} disabled={!editablePermissions.includes(code)}/><span>{label}</span></label>)}</fieldset>)}</div>; }
import Link from "next/link";
