"use client";
import { useState } from "react";
import styles from "./role-editor.module.css";
type ModuleOption = { key: string; name: string; description: string; sections: Array<{ label: string; items: Array<{ code: string; label: string }> }> };
export function RoleEditor({ modules, selectedModules, selectedPermissions, readOnly = false }: { modules: ModuleOption[]; selectedModules: string[]; selectedPermissions: string[]; readOnly?: boolean }) {
  const [activeModules, setActiveModules] = useState(selectedModules);
  const toggle = (key: string) => setActiveModules((items) => items.includes(key) ? items.filter((item) => item !== key) : [...items, key]);
  return <div className={styles.editor}><section><h2>Modül seçimi</h2><p>Rolün geçerli olacağı modülleri seçin. Yalnız firmanıza açık modüller listelenir.</p><div className={styles.moduleGrid}>{modules.map((module)=><label key={module.key} className={`${styles.moduleCard} ${activeModules.includes(module.key) ? styles.moduleCardActive : ""}`}><input type="checkbox" name="moduleKeys" value={module.key} checked={activeModules.includes(module.key)} onChange={()=>toggle(module.key)} disabled={readOnly}/><span><strong>{module.name}</strong><small>{module.description}</small></span></label>)}</div></section>{modules.filter((module)=>activeModules.includes(module.key)).map((module)=><section key={module.key} className={styles.modulePermissions}><div className={styles.moduleHeading}><h2>{module.name}</h2><p>Bu modüldeki ekran ve işlemleri seçin.</p></div><div className={styles.screenGrid}>{module.sections.map((section)=><fieldset key={section.label} className={styles.screenCard}><legend>{section.label}</legend>{section.items.map((item)=><label key={item.code} className={styles.permissionRow}><input type="checkbox" name="permissions" value={item.code} defaultChecked={selectedPermissions.includes(item.code)} disabled={readOnly}/><span>{item.label}</span></label>)}</fieldset>)}</div></section>)}</div>;
}
