import { notFound } from "next/navigation";
import { transferCompanyOwnershipAction, updateCompanyMembershipAction } from "@/app/dashboard/access-actions";
import { SubmitButton } from "@/app/dashboard/submit-button";
import { CompanyMembershipStatus, DataScopeMode } from "@/generated/prisma/client";
import { assertPermission } from "@/lib/authorization";
import { permissionLabel, PERMISSIONS } from "@/lib/permission-catalog";
import { prisma } from "@/lib/prisma";
import { requireSessionUser } from "@/lib/session";
import { MODULE_CATALOG } from "@/lib/module-catalog";
import styles from "../../../page.module.css";

export default async function MembershipDetailPage(props: { params: Promise<{ id: string }> }) {
  const { user, authorization } = await requireSessionUser(); assertPermission(authorization, PERMISSIONS.ACCESS_VIEW); if (!authorization.companyId) throw new Error("Aktif firma seçilmedi.");
  const membershipId = Number((await props.params).id);
  const [membership, roles, branches, departments, employees, devices, teams] = await Promise.all([
    prisma.companyMembership.findFirst({ where: { id: membershipId, companyId: authorization.companyId }, include: { user: true, role: { include: { permissions: true } }, employee: true, branchScopes: true, departmentScopes: true, employeeScopes: true, deviceScopes: true, teamScopes: true, modules: true } }),
    prisma.companyRole.findMany({ where: { companyId: authorization.companyId, isActive: true }, include: { permissions: true }, orderBy: { name: "asc" } }), prisma.branch.findMany({ where: { companyId: authorization.companyId, isActive: true }, orderBy: { name: "asc" } }), prisma.department.findMany({ where: { companyId: authorization.companyId, isActive: true }, orderBy: { name: "asc" } }), prisma.employee.findMany({ where: { companyId: authorization.companyId, isActive: true }, orderBy: [{ firstName: "asc" }, { lastName: "asc" }] }), prisma.device.findMany({ where: { companyId: authorization.companyId }, orderBy: { name: "asc" } }), prisma.companyTeam.findMany({ where: { companyId: authorization.companyId, isActive: true }, orderBy: { name: "asc" } }),
  ]);
  if (!membership) notFound();
  const canManage = authorization.permissions.has(PERMISSIONS.ACCESS_MANAGE); const isOwner = membership.role.key === "OWNER";
  const assignableRoles = roles.filter((role)=> role.key !== "OWNER" && role.permissions.every((permission)=>authorization.permissions.has(permission.permission)));
  return <div className={styles.page}><section className={`glass-panel ${styles.heroCard}`}><div><p className={styles.eyebrow}>Üyelik detayı</p><h1 className={styles.title}>{membership.user.firstName} {membership.user.lastName}</h1><p className={styles.subtitle}>{membership.user.email} · {membership.role.name}</p></div></section>
    <section className={styles.mainGrid}><div className={styles.primaryColumn}><section className={`glass-panel ${styles.sectionCard}`}><div className={styles.sectionHeader}><div><p className={styles.sectionEyebrow}>Efektif yetkiler</p><h2 className={styles.sectionTitle}>{membership.role.name}</h2></div></div><div className={styles.permissionSummary}>{membership.role.permissions.map((item)=><span key={item.permission} className={styles.reportBadgeSuccess}>{permissionLabel(item.permission)}</span>)}</div></section>
    {canManage && !isOwner ? <section className={`glass-panel ${styles.sectionCard}`}><form action={updateCompanyMembershipAction} className={styles.formGrid}><input type="hidden" name="membershipId" value={membership.id}/><label className={styles.field}><span>Rol</span><select name="roleId" defaultValue={membership.roleId}>{assignableRoles.map((role)=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><label className={styles.field}><span>Durum</span><select name="status" defaultValue={membership.status}>{Object.values(CompanyMembershipStatus).map((status)=><option key={status} value={status}>{status}</option>)}</select></label><label className={styles.field}><span>Kapsam modu</span><select name="scopeMode" defaultValue={membership.scopeMode}>{Object.values(DataScopeMode).map((mode)=><option key={mode} value={mode}>{mode}</option>)}</select></label><label className={styles.field}><span>Bağlı personel (OWN için)</span><select name="employeeId" defaultValue={membership.employeeId ?? ""}><option value="">Bağlantı yok</option>{employees.map((item)=><option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></label><ModuleChecks selected={membership.modules.map((item)=>item.moduleKey)}/><Checks title="Şubeler" name="branchIds" items={branches} selected={membership.branchScopes.map((item)=>item.branchId)}/><Checks title="Departmanlar" name="departmentIds" items={departments} selected={membership.departmentScopes.map((item)=>item.departmentId)}/><Checks title="Açık personeller" name="employeeIds" items={employees.map((item)=>({id:item.id,name:`${item.firstName} ${item.lastName}`}))} selected={membership.employeeScopes.map((item)=>item.employeeId)}/><Checks title="Ekipler" name="teamIds" items={teams} selected={membership.teamScopes.map((item)=>item.teamId)}/><Checks title="Cihazlar" name="deviceIds" items={devices} selected={membership.deviceScopes.map((item)=>item.deviceId)}/><div className={styles.fullWidthActionRow}><SubmitButton idleLabel="Rol, Modül ve Kapsamı Kaydet" pendingLabel="Kaydediliyor..." className={styles.primaryButton}/></div></form></section> : null}</div>
    <aside className={styles.sideColumn}>{isOwner ? <section className={`glass-panel ${styles.sectionCard}`}><p className={styles.sectionEyebrow}>Korunan rol</p><h2 className={styles.sectionTitle}>Firma sahibi</h2><p className={styles.helperText}>Sahip üyeliği askıya alınamaz veya normal rol formuyla değiştirilemez. Sahiplik yalnız açık devir işlemiyle aktarılır.</p>{membership.userId === user.id && authorization.permissions.has(PERMISSIONS.OWNERSHIP_TRANSFER) ? <form action={transferCompanyOwnershipAction} className={styles.formGrid}><label className={`${styles.field} ${styles.fullWidth}`}><span>Yeni firma sahibi</span><select name="targetMembershipId" required><option value="">Seçin</option>{(await prisma.companyMembership.findMany({where:{companyId:authorization.companyId,status:"ACTIVE",userId:{not:user.id}},include:{user:true}})).map((item)=><option key={item.id} value={item.id}>{item.user.email}</option>)}</select></label><SubmitButton idleLabel="Sahipliği Devret" pendingLabel="Devrediliyor..." className={styles.dangerButton}/></form> : null}</section> : null}</aside></section></div>;
}
function Checks({title,name,items,selected}:{title:string;name:string;items:Array<{id:number;name:string}>;selected:number[]}) { return <fieldset className={`${styles.scopeFieldset} ${styles.fullWidth}`}><legend>{title}</legend><div className={styles.permissionCheckGrid}>{items.map((item)=><label key={item.id} className={styles.checkField}><input type="checkbox" name={name} value={item.id} defaultChecked={selected.includes(item.id)}/><span>{item.name}</span></label>)}</div></fieldset>; }
function ModuleChecks({selected}:{selected:string[]}) { return <fieldset className={`${styles.scopeFieldset} ${styles.fullWidth}`}><legend>Kullanılabilir modüller</legend><div className={styles.permissionCheckGrid}>{MODULE_CATALOG.map((item)=><label key={item.key} className={styles.checkField}><input type="checkbox" name="moduleKeys" value={item.key} defaultChecked={selected.includes(item.key)}/><span><strong>{item.name}</strong><small className={styles.helperText}>{item.description}</small></span></label>)}</div></fieldset>; }
