import { Filter, LockKeyhole } from "lucide-react";
import { redirect } from "next/navigation";
import { PayrollPeriodStatus } from "@/generated/prisma/client";
import { approvePayrollPeriodAction, lockPayrollPeriodAction, reopenPayrollPeriodAction } from "@/app/dashboard/actions";
import { ExportButton } from "@/app/dashboard/export-button";
import { SubmitButton } from "@/app/dashboard/submit-button";
import { getAccessibleCompanyIds } from "@/lib/access";
import { buildPayrollSnapshot, getDefaultPayrollMonth, getPayrollMonthRange, normalizePayrollMonth, parsePayrollSnapshot } from "@/lib/payroll-period";
import { prisma } from "@/lib/prisma";
import { requireSessionUser } from "@/lib/session";
import styles from "../../page.module.css";

const statusLabels: Record<PayrollPeriodStatus, string> = { OPEN: "Açık", APPROVED: "Onaylandı", LOCKED: "Kilitli" };
function minutesText(value: number) { const hours = Math.floor(value / 60); const minutes = value % 60; return hours ? `${hours} sa ${minutes} dk` : `${minutes} dk`; }
function formatDate(value?: Date | null) { return value ? new Intl.DateTimeFormat("tr-TR", { dateStyle: "short", timeStyle: "short" }).format(value) : "—"; }

export default async function PayrollPage(props: { searchParams: Promise<{ month?: string; companyId?: string; branch?: string; department?: string }> }) {
  const { user } = await requireSessionUser();
  if (user.role !== "COMPANY_ADMIN") redirect("/dashboard");
  const companyIds = await getAccessibleCompanyIds(user);
  if (!companyIds?.length) redirect("/dashboard");
  const params = await props.searchParams;
  const monthKey = normalizePayrollMonth(params.month);
  const requestedCompanyId = Number(params.companyId);
  const companyId = Number.isSafeInteger(requestedCompanyId) && companyIds.includes(requestedCompanyId) ? requestedCompanyId : companyIds[0];
  const branch = params.branch?.trim() ?? "";
  const department = params.department?.trim() ?? "";
  const range = getPayrollMonthRange(monthKey);
  const [companies, branches, departments, period] = await Promise.all([
    prisma.company.findMany({ where: { id: { in: companyIds } }, orderBy: { name: "asc" } }),
    prisma.branch.findMany({ where: { companyId, isActive: true }, orderBy: { name: "asc" } }),
    prisma.department.findMany({ where: { companyId, isActive: true }, orderBy: { name: "asc" } }),
    prisma.payrollPeriod.findUnique({ where: { companyId_year_month: { companyId, year: range.year, month: range.month } }, include: { approvedBy: true, lockedBy: true } }),
  ]);
  const frozenSnapshot = parsePayrollSnapshot(period?.snapshotJson);
  const snapshot = frozenSnapshot ?? await buildPayrollSnapshot(companyId, monthKey);
  const summaryRows = snapshot.summaryRows.filter((row) => (!branch || row.branch === branch) && (!department || row.department === department));
  const employeeIds = new Set(summaryRows.map((row) => row.employeeId));
  const detailRows = snapshot.detailRows.filter((row) => employeeIds.has(row.employeeId));
  const returnTo = `/dashboard/reports/payroll?month=${monthKey}&companyId=${companyId}${branch ? `&branch=${encodeURIComponent(branch)}` : ""}${department ? `&department=${encodeURIComponent(department)}` : ""}`;
  const status = period?.status ?? PayrollPeriodStatus.OPEN;
  const totalLate = summaryRows.reduce((total, row) => total + row.lateMinutes, 0);
  const totalBreak = summaryRows.reduce((total, row) => total + row.breakMinutes, 0);
  const errorDays = summaryRows.reduce((total, row) => total + row.errorDays, 0);

  return <div className={styles.page}>
    <section className={`glass-panel ${styles.heroCard}`}><div><p className={styles.eyebrow}>Raporlar / Puantaj</p><h1 className={styles.title}>Aylık Puantaj Onayı</h1><p className={styles.subtitle}>Ayı kontrol edin, snapshot oluşturarak onaylayın ve kesinleştiğinde kilitleyin. Kilitli ayların hareketleri değiştirilemez.</p></div><div className={styles.heroMeta}><span className={status === PayrollPeriodStatus.LOCKED ? styles.reportBadgeDanger : status === PayrollPeriodStatus.APPROVED ? styles.reportBadgeSuccess : styles.reportBadgeWarning}>{statusLabels[status]}</span><ExportButton rows={summaryRows} columns={[{ key: "employee", label: "Personel" }, { key: "registrationNumber", label: "Sicil" }, { key: "branch", label: "Şube" }, { key: "department", label: "Departman" }, { key: "plannedDays", label: "Planlı Gün" }, { key: "attendedDays", label: "Çalışılan Gün" }, { key: "missingDays", label: "Eksik Gün" }, { key: "lateMinutes", label: "Geç Dakika" }, { key: "breakMinutes", label: "Mola Dakika" }, { key: "workedMinutes", label: "Çalışma Dakika" }, { key: "errorDays", label: "Hatalı Gün" }]} filename={`puantaj-ozet-${monthKey}`} className={styles.primaryLinkButton} label="Özet Dışa Aktar" /><ExportButton rows={detailRows} columns={[{ key: "employee", label: "Personel" }, { key: "registrationNumber", label: "Sicil" }, { key: "date", label: "Tarih" }, { key: "branch", label: "Şube" }, { key: "department", label: "Departman" }, { key: "dayType", label: "Gün Tipi" }, { key: "plannedStart", label: "Planlanan Giriş" }, { key: "plannedEnd", label: "Planlanan Çıkış" }, { key: "firstEntry", label: "İlk Giriş" }, { key: "lastExit", label: "Son Çıkış" }, { key: "lateMinutes", label: "Geç Dakika" }, { key: "breakMinutes", label: "Mola Dakika" }, { key: "workedMinutes", label: "Çalışma Dakika" }, { key: "movementCount", label: "Hareket Adedi" }, { key: "movements", label: "Hareketler" }, { key: "issues", label: "Kontrol Durumu" }]} filename={`puantaj-detay-${monthKey}`} className={styles.primaryLinkButton} label="Ayrıntılı Dışa Aktar" /></div></section>
    <section className={`glass-panel ${styles.sectionCard}`}><form className={styles.filterGrid}><label className={styles.field}><span>Dönem</span><input type="month" name="month" defaultValue={monthKey} max={getDefaultPayrollMonth()} /></label><label className={styles.field}><span>Firma</span><select name="companyId" defaultValue={companyId}>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className={styles.field}><span>Şube</span><select name="branch" defaultValue={branch}><option value="">Tüm şubeler</option>{branches.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label className={styles.field}><span>Departman</span><select name="department" defaultValue={department}><option value="">Tüm departmanlar</option>{departments.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label><button type="submit" className={styles.primaryButton}><Filter size={16} /> Raporu Getir</button></form></section>
    <section className={styles.metricsGrid}><article className={`glass-panel ${styles.metricCard}`}><p className={styles.metricLabel}>Personel</p><p className={styles.metricValue}>{summaryRows.length}</p></article><article className={`glass-panel ${styles.metricCard}`}><p className={styles.metricLabel}>Toplam Gecikme</p><p className={styles.metricValue}>{minutesText(totalLate)}</p></article><article className={`glass-panel ${styles.metricCard}`}><p className={styles.metricLabel}>Toplam Mola</p><p className={styles.metricValue}>{minutesText(totalBreak)}</p></article><article className={`glass-panel ${styles.metricCard}`}><p className={styles.metricLabel}>Kontrol Gerektiren Gün</p><p className={styles.metricValue}>{errorDays}</p></article></section>
    <section className={`glass-panel ${styles.sectionCard}`}><div className={styles.sectionHeader}><div><p className={styles.sectionEyebrow}>Dönem işlemleri</p><h2 className={styles.sectionTitle}>{monthKey} · {statusLabels[status]}</h2></div></div>{status === PayrollPeriodStatus.OPEN ? <form action={approvePayrollPeriodAction} className={styles.payrollActionForm}><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="month" value={monthKey} /><input type="hidden" name="returnTo" value={returnTo} /><input name="approvalNote" required placeholder="Kontrol / onay açıklaması" /><SubmitButton idleLabel="Dönemi Onayla" pendingLabel="Snapshot oluşturuluyor..." className={styles.primaryButton} /></form> : status === PayrollPeriodStatus.APPROVED ? <div className={styles.payrollActionRow}><form action={reopenPayrollPeriodAction}><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="month" value={monthKey} /><input type="hidden" name="returnTo" value={returnTo} /><SubmitButton idleLabel="Onayı Geri Al" pendingLabel="Açılıyor..." className={styles.smallButton} /></form><form action={lockPayrollPeriodAction}><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="month" value={monthKey} /><input type="hidden" name="returnTo" value={returnTo} /><SubmitButton idleLabel="Dönemi Kilitle" pendingLabel="Kilitleniyor..." className={styles.dangerButton} /></form></div> : <p className={styles.helperText}><LockKeyhole size={16} /> Bu dönem kilitlidir. Hareket ekleme, silme ve tarih/tip düzenleme işlemleri engellenir.</p>}<div className={styles.detailList}><p><span>Snapshot</span>{frozenSnapshot ? formatDate(period?.snapshotCreatedAt) : "Canlı hesaplama"}</p><p><span>Onaylayan</span>{period?.approvedBy?.name ?? period?.approvedBy?.email ?? "—"} · {formatDate(period?.approvedAt)}</p><p><span>Kilitleyen</span>{period?.lockedBy?.name ?? period?.lockedBy?.email ?? "—"} · {formatDate(period?.lockedAt)}</p><p><span>Açıklama</span>{period?.approvalNote ?? "—"}</p></div></section>
    <section className={`glass-panel ${styles.sectionCard}`}><div className={styles.sectionHeader}><div><p className={styles.sectionEyebrow}>Personel özeti</p><h2 className={styles.sectionTitle}>Aylık Sonuçlar</h2></div><div className={styles.countPill}>{summaryRows.length} personel</div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Personel</th><th>Planlı / Çalışılan</th><th>Eksik Gün</th><th>Geç Kalma</th><th>Mola</th><th>Net Çalışma</th><th>Hatalı Gün</th></tr></thead><tbody>{summaryRows.length === 0 ? <tr><td colSpan={7} className={styles.emptyCell}>Bu dönemde personel verisi bulunamadı.</td></tr> : summaryRows.map((row) => <tr key={row.employeeId}><td><strong>{row.employee}</strong><p className={styles.tableSubText}>{row.registrationNumber} · {row.department} · {row.branch}</p></td><td>{row.plannedDays} / {row.attendedDays}</td><td>{row.missingDays}</td><td>{row.lateDays} gün · {row.lateMinutes} dk</td><td>{minutesText(row.breakMinutes)}</td><td>{minutesText(row.workedMinutes)}</td><td><span className={row.errorDays ? styles.reportBadgeDanger : styles.reportBadgeSuccess}>{row.errorDays}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
