import Link from "next/link";
import { deleteWorkCenterAction, updateWorkCenterAction } from "@/modules/production/actions";
import { assertPermission } from "@/lib/authorization";
import { PERMISSIONS } from "@/lib/permission-catalog";
import { requireSessionUser } from "@/lib/session";
import { queryRepository } from "@/modules/shared/query-repository";
import ui from "../../../../management.module.css";

export default async function Page({params}:{params:Promise<{id:string}>}) { const {authorization}=await requireSessionUser();assertPermission(authorization,PERMISSIONS.WORK_CENTER_VIEW);if(!authorization.companyId)throw new Error("Aktif firma seçilmedi.");const id=Number((await params).id);const [item,calendars]=await Promise.all([queryRepository.productionWorkCenter.findFirst({where:{id,companyId:authorization.companyId}}),queryRepository.workCalendarTemplate.findMany({where:{companyId:authorization.companyId,isActive:true},select:{id:true,name:true}})]);if(!item)throw new Error("İş merkezi bulunamadı.");const manage=authorization.isPlatformAdmin||authorization.permissions.has(PERMISSIONS.WORK_CENTER_MANAGE);return <div className={ui.managementPage}><header className={ui.pageHeader}><div className={ui.headerCopy}><p className={ui.kicker}>İş Merkezi</p><h1 className={ui.pageTitle}>{item.name}</h1></div><Link className={ui.secondaryAction} href="/dashboard/production/definitions/work-centers">Listeye dön</Link></header>{manage&&<><section className={ui.surface}><form action={updateWorkCenterAction} className={ui.formGrid}><input type="hidden" name="id" value={item.id}/><label className={ui.formField}><span>Kod</span><input name="code" required defaultValue={item.code}/></label><label className={ui.formField}><span>Ad</span><input name="name" required defaultValue={item.name}/></label><label className={ui.formField}><span>Takvim</span><select name="calendarTemplateId" defaultValue={item.calendarTemplateId??""}><option value="">Firma varsayılanı</option>{calendars.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className={ui.checkField}><input name="isActive" type="checkbox" defaultChecked={item.isActive}/> Aktif</label><label className={`${ui.formField} ${ui.formFullWidth}`}><span>Açıklama</span><textarea name="description" defaultValue={item.description??""}/></label><div className={ui.formActions}><button className={ui.primaryAction}>Kaydet</button></div></form></section><section className={ui.dangerZone}><div><h3>İş merkezini sil</h3><p>Kullanımdaki kayıtlar silinemez; pasife alınmalıdır.</p></div><form action={deleteWorkCenterAction}><input type="hidden" name="id" value={item.id}/><button className={ui.dangerAction}>Sil</button></form></section></>}</div>; }
