import Link from "next/link";
import { createWorkCenterAction } from "@/modules/production/actions";
import { assertPermission } from "@/lib/authorization";
import { PERMISSIONS } from "@/lib/permission-catalog";
import { requireSessionUser } from "@/lib/session";
import { queryRepository } from "@/modules/shared/query-repository";
import ui from "../../../management.module.css";

export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
 const { authorization }=await requireSessionUser(); assertPermission(authorization,PERMISSIONS.WORK_CENTER_VIEW); if(!authorization.companyId) throw new Error("Aktif firma seçilmedi."); const q=(await searchParams).q?.trim()??""; const canManage=authorization.isPlatformAdmin||authorization.permissions.has(PERMISSIONS.WORK_CENTER_MANAGE); const [items,calendars]=await Promise.all([queryRepository.productionWorkCenter.findMany({where:{companyId:authorization.companyId,...(q?{OR:[{code:{contains:q}},{name:{contains:q}}]}:{})},orderBy:[{isActive:"desc"},{name:"asc"}]}),queryRepository.workCalendarTemplate.findMany({where:{companyId:authorization.companyId,isActive:true},select:{id:true,name:true}})]);
 return <div className={ui.managementPage}><header className={ui.pageHeader}><div className={ui.headerCopy}><p className={ui.kicker}>Sabit Tanımlar</p><h1 className={ui.pageTitle}>İş Merkezleri</h1><p className={ui.pageDescription}>İş merkezlerini arayın, yeni kayıt ekleyin ve yönetin.</p></div><div className={ui.headerActions}><Link className={ui.secondaryAction} href="/dashboard/production/definitions">Sabit tanımlar</Link></div></header>{canManage&&<section className={ui.surface}><form action={createWorkCenterAction} className={ui.formGrid}><label className={ui.formField}><span>Kod</span><input name="code" required/></label><label className={ui.formField}><span>Ad</span><input name="name" required/></label><label className={ui.formField}><span>Takvim</span><select name="calendarTemplateId"><option value="">Firma varsayılanı</option>{calendars.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className={ui.primaryAction}>Yeni iş merkezi</button></form></section>}<section className={ui.surface}><form className={ui.searchFilterBar}><label className={ui.field}><span className={ui.fieldLabel}>Ara</span><input className={ui.control} name="q" defaultValue={q} placeholder="Kod veya ad"/></label><button className={ui.filterButton}>Ara</button></form><div className={ui.tableWrap}><table className={ui.dataTable}><thead><tr><th>Kod</th><th>Ad</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.isActive?"Aktif":"Pasif"}</td><td><Link className={ui.rowAction} href={`/dashboard/production/definitions/work-centers/${x.id}`}>İncele</Link></td></tr>)}</tbody></table></div></section></div>;
}
