import { ActionForm } from "@/app/dashboard/action-form";
import { saveCompanyTeamAction } from "@/app/dashboard/access-actions";
import { SubmitButton } from "@/app/dashboard/submit-button";
import { redirect } from "next/navigation";
import { PERMISSIONS } from "@/lib/permission-catalog";
import { prisma } from "@/lib/prisma";
import { requireSessionUser } from "@/lib/session";
import styles from "../../page.module.css";
export default async function TeamsPage() { const { authorization } = await requireSessionUser(); if (!authorization.permissions.has(PERMISSIONS.ACCESS_MANAGE)) redirect("/dashboard/access"); if (!authorization.companyId) throw new Error("Aktif firma seçilmedi."); const [teams, employees] = await Promise.all([prisma.companyTeam.findMany({where:{companyId:authorization.companyId},include:{members:true},orderBy:{name:"asc"}}),prisma.employee.findMany({where:{companyId:authorization.companyId,isActive:true},orderBy:[{firstName:"asc"},{lastName:"asc"}]})]); return <div className={styles.page}><section className={`glass-panel ${styles.heroCard}`}><div><p className={styles.eyebrow}>Veri kapsamı</p><h1 className={styles.title}>Ekip Tanımları</h1><p className={styles.subtitle}>Ekip ilişkileri doğrulanabilir personel kimlikleriyle tutulur; managerName metni yetki kaynağı değildir.</p></div></section><section className={`glass-panel ${styles.sectionCard}`}><ActionForm action={saveCompanyTeamAction} className={styles.formGrid}><label className={styles.field}><span>Yeni ekip adı</span><input name="name" required/></label><EmployeeChecks employees={employees} selected={[]}/><div className={styles.fullWidthActionRow}><SubmitButton idleLabel="Ekip Oluştur" pendingLabel="Kaydediliyor..." className={styles.primaryButton}/></div></ActionForm></section><div className={styles.reviewCaseList}>{teams.map((team)=><section key={team.id} className={`glass-panel ${styles.sectionCard}`}><ActionForm action={saveCompanyTeamAction} className={styles.formGrid}><input type="hidden" name="teamId" value={team.id}/><label className={styles.field}><span>Ekip adı</span><input name="name" defaultValue={team.name} required/></label><label className={styles.checkField}><input type="checkbox" name="isActive" defaultChecked={team.isActive}/><span>Aktif</span></label><EmployeeChecks employees={employees} selected={team.members.map((item)=>item.employeeId)}/><div className={styles.fullWidthActionRow}><SubmitButton idleLabel="Ekibi Güncelle" pendingLabel="Kaydediliyor..." className={styles.smallButton}/></div></ActionForm></section>)}</div></div>; }
function EmployeeChecks({employees,selected}:{employees:Array<{id:number;firstName:string;lastName:string}>;selected:number[]}) { return <fieldset className={`${styles.scopeFieldset} ${styles.fullWidth}`}><legend>Personeller</legend><div className={styles.permissionCheckGrid}>{employees.map((item)=><label key={item.id} className={styles.checkField}><input type="checkbox" name="employeeIds" value={item.id} defaultChecked={selected.includes(item.id)}/><span>{item.firstName} {item.lastName}</span></label>)}</div></fieldset>; }
